//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_V_2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHinhWeb
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public string Loai { get; set; }
        public string GiaTri { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
