//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_V_2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int MaGioHang { get; set; }
        public int maSanPham { get; set; }
        public string tenSanPham { get; set; }
        public string HinhAnh { get; set; }
        public decimal DonGia { get; set; }
        public int SoLuong { get; set; }
        public decimal ThanhTien { get; set; }
        public string TenDangNhap { get; set; }
    }
}
