//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_V_2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhienDangNhap
    {
        public string Token { get; set; }
        public string TenDangNhap { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string DiaChiIP { get; set; }
        public int ID { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
