//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_V_2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public long MaSP { get; set; }
        public long MaLoai { get; set; }
        public string TenSP { get; set; }
        public string Mota { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<decimal> GiaGiam { get; set; }
        public string HinhAnh { get; set; }
        public string HinhAnhThem { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> TonKho { get; set; }
        public Nullable<bool> BanChay { get; set; }
        public Nullable<bool> Moi { get; set; }
        public Nullable<bool> Hot { get; set; }
        public Nullable<bool> KhuyenMai { get; set; }
        public string ChiTietSanPham { get; set; }
        public Nullable<int> BaoHanh { get; set; }
        public Nullable<System.DateTime> TopHot { get; set; }
        public Nullable<bool> DaCoVAT { get; set; }
        public string TieuDeMeta { get; set; }
        public string IDMenuCha { get; set; }
        public string TieuDeSeo { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<bool> HienThiTrenTrangChu { get; set; }
        public string MetaKeyWord { get; set; }
        public string MeTaDescription { get; set; }
        public Nullable<int> SoLuotXem { get; set; }
    
        public virtual LoaiHang LoaiHang { get; set; }
    }
}
