//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_V_2018.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHang
    {
        public int ID { get; set; }
        public string TenCuaHang { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string MoTa { get; set; }
        public string Logo { get; set; }
        public string HotLine { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string LinkMap { get; set; }
        public string Website { get; set; }
    }
}
