//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_V_2018.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiHang()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public long MaLoai { get; set; }
        public string TenLoai { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public bool NoiBat { get; set; }
        public string TieuDeMeta { get; set; }
        public string IDMenuCha { get; set; }
        public string TieuDeSeo { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> HienThiTrenTrangChu { get; set; }
        public string MetaKeyWord { get; set; }
        public string MeTaDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
