//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_V_2018.Views
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Vuong_CTK39Entities1 : DbContext
    {
        public Vuong_CTK39Entities1()
            : base("name=Vuong_CTK39Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CauHinhWeb> CauHinhWebs { get; set; }
        public virtual DbSet<ChinhSua> ChinhSuas { get; set; }
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DbSet<CuaHang> CuaHangs { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<GioHang> GioHangs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<LoaiHang> LoaiHangs { get; set; }
        public virtual DbSet<LoaiMenu> LoaiMenus { get; set; }
        public virtual DbSet<LoaiSlide> LoaiSlides { get; set; }
        public virtual DbSet<LoaiTinTuc> LoaiTinTucs { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<PhienDangNhap> PhienDangNhaps { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TagContent> TagContents { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TaiKhanMXH> TaiKhanMXHs { get; set; }
        public virtual DbSet<TaiKhoanNganHang> TaiKhoanNganHangs { get; set; }
        public virtual DbSet<TinTuc> TinTucs { get; set; }
    }
}
