//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_V_2018.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanNganHang
    {
        public int ID { get; set; }
        public string NganHang { get; set; }
        public string ChuTaiKhoan { get; set; }
        public string SoTaiKhoan { get; set; }
        public string ChiNhanh { get; set; }
    }
}
